commonLabels:
  app: nodejs-ex-kustomize

resources:
  - templates/service.yaml
  - templates/buildconfig.yaml
  - templates/imagestream.yaml

configurations: 
  - kustomizeconfig/imagestream.yaml
  - kustomizeconfig/buildconfig.yaml
  - kustomizeconfig/deploymentconfig.yaml